--
-- File generated with SQLiteStudio v3.0.6 on Sun Sep 20 19:23:50 2015
--
-- Text encoding used: windows-1252
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: ShipmentTypes
CREATE TABLE [ShipmentTypes] ([ShipmentType_ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [ShipmentType] TEXT NOT NULL ON CONFLICT ABORTABORT)

-- Table: Modules
CREATE TABLE [Modules] ([Mod_ID] INTEGER PRIMARY KEY AUTOINCREMENT, [ModuleName] VARCHAR NOT NULL ON CONFLICT ABORTABORT UNIQUE ON CONFLICT ABORTABORT, [EnableModNotification] BOOLEAN DEFAULT(1))

-- Table: RptConfig
CREATE TABLE RptConfig (RptConfig_ID INTEGER PRIMARY KEY AUTOINCREMENT, DistributionTypeID INTEGER NOT NULL ON CONFLICT ABORTABORT REFERENCES DistributionTypes (DistributionType_ID) ON DELETE CASCADE ON UPDATE CASCADE, RptActionsID INTEGER REFERENCES RptActions (RptAction_ID) ON UPDATE CASCADE)

-- Table: EmailNotifications
CREATE TABLE [EmailNotifications] ([EN_ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [ModuleName] VARCHAR NOT NULL, [EventName] VARCHAR NOT NULL UNIQUE ON CONFLICT ABORTABORT, [EventNotification] BOOLEAN NOT NULL, [EmailFrom] VARCHAR NOT NULL ON CONFLICT ABORTABORT, [EmailTo] VARCHAR NOT NULL ON CONFLICT ABORTABORT, [EmailSubject] VARCHAR NOT NULL ON CONFLICT ABORTABORT, [EmailBody] VARCHAR NOT NULL ON CONFLICT ABORTABORT)

-- Table: UOM
CREATE TABLE [UOM] ([UOM_ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [UOM] VARCHAR NOT NULL UNIQUE ON CONFLICT ABORTABORT)

-- Table: IntlLicense
CREATE TABLE [IntlLicense] ([License_ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [LicenseAbbr] VARCHAR NOT NULL UNIQUE ON CONFLICT ABORTABORT, [LicenseDesc] VARCHAR)

-- Table: Carriers
CREATE TABLE Carriers (Carrier_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT NOT NULL ON CONFLICT ABORTABORT UNIQUE ON CONFLICT ABORTABORT, RateType VARCHAR, RateTable VARCHAR)

-- Table: Users
CREATE TABLE Users (User_ID INTEGER PRIMARY KEY AUTOINCREMENT, UserLogin TEXT UNIQUE ON CONFLICT ABORTABORT NOT NULL ON CONFLICT ABORTABORT, UserName TEXT, UserEmail TEXT, UserPwd TEXT NOT NULL ON CONFLICT ABORTABORT, UserSalt TEXT, User_Status BOOLEAN DEFAULT (1))

-- Table: FreightRates
CREATE TABLE [FreightRates] ([RateTable_ID] REFERENCES [CarrierName] ([RateTable]), [WeightLow1] INTEGER, [WeightHigh1] INTEGER, [ShippingCost] VARCHAR)

-- Table: Countries
CREATE TABLE [Countries] ([Country_ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [CountryCode] VARCHAR (2) NOT NULL UNIQUE, [CountryName] TEXT NOT NULL)

-- Table: _OLD_Headers
CREATE TABLE _OLD_Headers (Header_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, InternalHeaderName TEXT NOT NULL UNIQUE ON CONFLICT ABORTABORT, HeaderMaxLength INTEGER NOT NULL ON CONFLICT ABORTABORT, OutputHeaderName TEXT NOT NULL ON CONFLICT ABORTABORT, Widget TEXT NOT NULL ON CONFLICT ABORTABORT, Highlight TEXT, AlwaysDisplay BOOLEAN, Required BOOLEAN, DefaultWidth INTEGER, ResizeColumn BOOLEAN, DisplayOrder INTEGER)

-- Table: DistributionTypes
CREATE TABLE DistributionTypes (DistributionType_ID INTEGER PRIMARY KEY AUTOINCREMENT, DistTypeName TEXT UNIQUE ON CONFLICT ABORTABORT NOT NULL ON CONFLICT ABORTABORT, DistType_Status BOOLEAN DEFAULT (1) NOT NULL ON CONFLICT ABORTABORT, DistType_ShipTypeID INTEGER REFERENCES ShipmentTypes (ShipmentType_ID) ON UPDATE CASCADE)

-- Table: DistributionTypeCarriers
CREATE TABLE DistributionTypeCarriers (DistributionTypesCarriers_ID INTEGER PRIMARY KEY AUTOINCREMENT, DistributionTypeID INTEGER NOT NULL ON CONFLICT ROLLBACKROLLBACK REFERENCES DistributionTypes (DistributionType_ID) ON DELETE CASCADE ON UPDATE CASCADE, CarrierID INTEGER REFERENCES Carriers (Carrier_ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL ON CONFLICT ROLLBACKROLLBACK, ShipViaID INTEGER REFERENCES ShipVia (ShipVia_ID) ON DELETE CASCADE ON UPDATE CASCADE)

-- Table: EmailSetup
CREATE TABLE [EmailSetup] ([Email_ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [EmailServer] VARCHAR NOT NULL, [EmailPassword] VARCHAR, [EmailPort] INTEGER, [EmailLogin] VARCHAR, [GlobalEmailNotification] BOOLEAN NOT NULL DEFAULT(1), [TLS] BOOLEAN DEFAULT(0))

-- Table: _OLD_AccountNumbers
CREATE TABLE _OLD_AccountNumbers (AcctNumbers_ID INTEGER PRIMARY KEY AUTOINCREMENT, CompaniesID INTEGER REFERENCES MasterAddresses (MasterAddr_ID) ON UPDATE CASCADE, CarriersID INTEGER REFERENCES Carriers (Carrier_ID) ON UPDATE CASCADE, AcctNumber TEXT)

-- Table: FreightPayer
CREATE TABLE [FreightPayer] ([FreightPayer_ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [Payer] TEXT NOT NULL ON CONFLICT ABORTABORT)

-- Table: RptAddresses
CREATE TABLE RptAddresses (RptAddress_ID INTEGER PRIMARY KEY AUTOINCREMENT, RptConfigID INTEGER REFERENCES RptConfig (RptConfig_ID) ON DELETE CASCADE ON UPDATE CASCADE, MasterAddrID INTEGER REFERENCES MasterAddresses (MasterAddr_ID) ON DELETE CASCADE ON UPDATE CASCADE, ShipViaID INTEGER REFERENCES ShipVia (ShipVia_ID) ON DELETE CASCADE ON UPDATE CASCADE)

-- Table: RptActions
CREATE TABLE RptActions (RptAction_ID INTEGER PRIMARY KEY AUTOINCREMENT, RptAction TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, RptMethodID INTEGER REFERENCES RptMethod (RptMethod_ID) ON UPDATE CASCADE)

-- Table: CarrierAccts
CREATE TABLE CarrierAccts (CarrierAccts_ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACKROLLBACK AUTOINCREMENT, CarrierAccts_Acct TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, Active BOOLEAN NOT NULL ON CONFLICT ROLLBACKROLLBACK DEFAULT (1), MasterAddrID INTEGER REFERENCES MasterAddresses (MasterAddr_ID) ON UPDATE CASCADE, CarrierID INTEGER REFERENCES Carriers (Carrier_ID) ON UPDATE CASCADE)

-- Table: EventNotifications
CREATE TABLE EventNotifications (Event_ID INTEGER PRIMARY KEY AUTOINCREMENT, ModID INTEGER NOT NULL ON CONFLICT ABORTABORT REFERENCES Modules (Mod_ID), EventName VARCHAR NOT NULL ON CONFLICT ABORTABORT, EventSubstitutions VARCHAR, EnableEventNotification BOOLEAN DEFAULT (1))

-- Table: Packages
CREATE TABLE [Packages] ([Pkg_ID] INTEGER PRIMARY KEY AUTOINCREMENT, [Package] TEXT NOT NULL ON CONFLICT ABORTABORT)

-- Table: SecGroups
CREATE TABLE SecGroups (SecGrp_ID INTEGER PRIMARY KEY AUTOINCREMENT, SecGroupNameID INTEGER NOT NULL ON CONFLICT ABORTABORT REFERENCES SecGroupNames (SecGroupName_ID) ON UPDATE CASCADE, UserID INTEGER NOT NULL ON CONFLICT ABORTABORT REFERENCES Users (User_ID) ON UPDATE CASCADE)

-- Table: SecGroupNames
CREATE TABLE SecGroupNames (SecGroupName_ID INTEGER PRIMARY KEY AUTOINCREMENT, SecGroupName TEXT UNIQUE ON CONFLICT ROLLBACKROLLBACK NOT NULL ON CONFLICT ROLLBACKROLLBACK, Status BOOLEAN DEFAULT (1) NOT NULL ON CONFLICT ROLLBACKROLLBACK)

-- Table: Customer
CREATE TABLE Customer (Cust_ID TEXT PRIMARY KEY NOT NULL ON CONFLICT ABORTABORT UNIQUE ON CONFLICT ABORTABORT, CustName TEXT NOT NULL ON CONFLICT ABORTABORT, Status BOOLEAN)

-- Table: RateTypes
CREATE TABLE [RateTypes] ([RateType_ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [RateType] TEXT NOT NULL ON CONFLICT ABORTABORT)

-- Table: ForestType
CREATE TABLE ForestType (ForestType_ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACKROLLBACK AUTOINCREMENT NOT NULL ON CONFLICT ROLLBACKROLLBACK UNIQUE ON CONFLICT ROLLBACKROLLBACK, ForestTypeDesc TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, Active BOOLEAN NOT NULL ON CONFLICT ROLLBACKROLLBACK DEFAULT (1), ForestOrgID INTEGER REFERENCES ForestOrg (ForestOrg_ID) ON UPDATE CASCADE NOT NULL ON CONFLICT ROLLBACKROLLBACK)

-- Table: ShipVia
CREATE TABLE ShipVia (ShipVia_ID INTEGER PRIMARY KEY AUTOINCREMENT, CarrierID INTEGER REFERENCES Carriers (Carrier_ID) ON DELETE CASCADE ON UPDATE CASCADE, ShipViaCode TEXT UNIQUE ON CONFLICT ABORTABORT, FreightPayerType TEXT NOT NULL ON CONFLICT ABORTABORT, ShipViaName TEXT NOT NULL ON CONFLICT ABORTABORT, ShipmentType TEXT NOT NULL ON CONFLICT ABORTABORT, RateType TEXT, RateTable TEXT)

-- Table: CSRs
CREATE TABLE CSRs (CSR_ID VARCHAR (6, 0) PRIMARY KEY ON CONFLICT ABORTABORT NOT NULL UNIQUE ON CONFLICT ABORTABORT, FirstName VARCHAR NOT NULL, LastName VARCHAR, Email VARCHAR, Status BOOLEAN DEFAULT (1))

-- Table: SubHeaders
CREATE TABLE SubHeaders (SubHeaderName VARCHAR UNIQUE ON CONFLICT ROLLBACKROLLBACK PRIMARY KEY ASC ON CONFLICT ROLLBACKROLLBACK COLLATE NOCASE, HeaderConfigID TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK REFERENCES HeadersConfig (HeaderConfig_ID) ON UPDATE CASCADE)

-- Table: Containers
CREATE TABLE [Containers] ([Container_ID] INTEGER PRIMARY KEY AUTOINCREMENT, [Container] TEXT NOT NULL ON CONFLICT ABORTABORT)

-- Table: ForestOrg
CREATE TABLE ForestOrg (ForestOrg_ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ON CONFLICT ROLLBACKROLLBACK NOT NULL ON CONFLICT ROLLBACKROLLBACK, ForestOrgName TEXT UNIQUE ON CONFLICT ROLLBACKROLLBACK NOT NULL ON CONFLICT ROLLBACKROLLBACK, ForestOrgNum TEXT UNIQUE ON CONFLICT ROLLBACKROLLBACK NOT NULL ON CONFLICT ROLLBACKROLLBACK, Active BOOLEAN NOT NULL ON CONFLICT ROLLBACKROLLBACK DEFAULT (1))

-- Table: RptMethod
CREATE TABLE RptMethod (RptMethod_ID INTEGER PRIMARY KEY AUTOINCREMENT, RptMethod TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK)

-- Table: Reports
CREATE TABLE Reports (Reports_ID INTEGER PRIMARY KEY AUTOINCREMENT, Reports_Name TEXT NOT NULL ON CONFLICT ABORTABORT UNIQUE ON CONFLICT ABORTABORT, Reports_Status BOOLEAN NOT NULL ON CONFLICT ABORTABORT DEFAULT (1))

-- Table: ShippingClasses
CREATE TABLE [ShippingClasses] ([ShippingClass_ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [ShippingClass] TEXT NOT NULL ON CONFLICT ABORTABORT)

-- Table: HeadersConfig
CREATE TABLE HeadersConfig (HeaderConfig_ID TEXT NOT NULL PRIMARY KEY ON CONFLICT ROLLBACKROLLBACK UNIQUE ON CONFLICT ROLLBACKROLLBACK, dbColName TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK UNIQUE ON CONFLICT ROLLBACKROLLBACK, dbDataType TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, widLabelName TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK UNIQUE ON CONFLICT ROLLBACKROLLBACK, widLabelAlignment TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, widWidget TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, widValues TEXT, widDataType TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, widFormat TEXT, widColAlignment TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, widStartColWidth INTEGER NOT NULL ON CONFLICT ROLLBACKROLLBACK, widMaxWidth INTEGER NOT NULL ON CONFLICT ROLLBACKROLLBACK, widResizeToLongestEntry BOOLEAN NOT NULL ON CONFLICT ROLLBACKROLLBACK DEFAULT (0), widMaxStringLength INTEGER NOT NULL ON CONFLICT ROLLBACKROLLBACK, widHighlightColor TEXT, widUIGroup TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, widUIPositionWeight INTEGER NOT NULL ON CONFLICT ROLLBACKROLLBACK DEFAULT (0), widExportable BOOLEAN NOT NULL ON CONFLICT ROLLBACKROLLBACK DEFAULT (1), widRequired BOOLEAN NOT NULL ON CONFLICT ROLLBACKROLLBACK DEFAULT (0), widDisplayType TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, dbActive BOOLEAN NOT NULL ON CONFLICT ROLLBACKROLLBACK DEFAULT (1))

-- Table: CustomerShipVia
CREATE TABLE CustomerShipVia (CustomerShipVia_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, CustID INTEGER REFERENCES Customer (Cust_ID), ShipViaID INTEGER REFERENCES ShipVia (ShipVia_ID))

-- Table: Provinces
CREATE TABLE [Provinces] ([Prov_ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [ProvAbbr] CHAR (3) NOT NULL, [ProvName] TEXT NOT NULL, [PostalCodeLowEnd] TEXT, [PostalCodeHighEnd] TEXT, [CountryID] INTEGER REFERENCES [Countries] ([Country_ID]) ON DELETE CASCADE)

-- Table: UserDefinedValues
CREATE TABLE UserDefinedValues (UserDefinedValue_ID INTEGER PRIMARY KEY AUTOINCREMENT, PrimaryKeyName TEXT UNIQUE ON CONFLICT ROLLBACKROLLBACK NOT NULL ON CONFLICT ROLLBACKROLLBACK, TableName TEXT UNIQUE ON CONFLICT ROLLBACKROLLBACK NOT NULL ON CONFLICT ROLLBACKROLLBACK, Description TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK UNIQUE ON CONFLICT ROLLBACKROLLBACK, DisplayColValues TEXT)

-- Table: IntlShipTerms
CREATE TABLE [IntlShipTerms] ([Terms_ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [TermsAbbr] VARCHAR NOT NULL UNIQUE ON CONFLICT ABORTABORT, [TermsDesc] VARCHAR, [IncoTerms] INTEGER)

-- Table: MasterAddresses
CREATE TABLE MasterAddresses (MasterAddr_ID INTEGER PRIMARY KEY AUTOINCREMENT, MasterAddr_Company TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, MasterAddr_Attn TEXT, MasterAddr_Addr1 TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, MasterAddr_Addr2 TEXT, MasterAddr_Addr3 TEXT, MasterAddr_City TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, MasterAddr_StateAbbr TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, MasterAddr_Zip TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, MasterAddr_CtryCode TEXT REFERENCES Countries (CountryCode) ON UPDATE CASCADE NOT NULL ON CONFLICT ROLLBACKROLLBACK, MasterAddr_Phone TEXT, MasterAddr_Plant BOOLEAN NOT NULL ON CONFLICT ROLLBACKROLLBACK DEFAULT (0), MasterAddr_Active BOOLEAN DEFAULT (1) NOT NULL ON CONFLICT ROLLBACKROLLBACK, MasterAddr_Internal BOOLEAN DEFAULT (0) NOT NULL ON CONFLICT ROLLBACKROLLBACK)

-- Table: PubTitle
CREATE TABLE PubTitle (Title_ID INTEGER PRIMARY KEY AUTOINCREMENT, TitleName TEXT NOT NULL ON CONFLICT ABORTABORT, CustID TEXT REFERENCES Customer (Cust_ID), Status BOOLEAN, CSRID VARCHAR REFERENCES CSRs (CSR_ID), SaveLocation TEXT)

-- Table: _OLD_PostalCodes
CREATE TABLE [_OLD_PostalCodes] ([PostalCode_ID] INTEGER PRIMARY KEY AUTOINCREMENT, [ProvID] INTEGER NOT NULL ON CONFLICT ABORTABORT REFERENCES [Provinces] ([Prov_ID]), [PostalCodeLow] TEXT, [PostalCodeHigh] TEXT, [CountryID] INTEGER NOT NULL ON CONFLICT ABORTABORT REFERENCES [Countries] ([Country_ID]))

-- Table: DbVersion
CREATE TABLE DbVersion (idx INTEGER PRIMARY KEY AUTOINCREMENT, Date DATE NOT NULL ON CONFLICT ROLLBACKROLLBACK, ProgramVers TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, SchemaVers TEXT NOT NULL ON CONFLICT ROLLBACKROLLBACK, FileName TEXT, UserID INTEGER REFERENCES Users (User_ID) ON UPDATE CASCADE NOT NULL ON CONFLICT ROLLBACKROLLBACK)

-- Table: SecurityAccess
CREATE TABLE SecurityAccess (SecAccess_ID INTEGER PRIMARY KEY AUTOINCREMENT, SecGrpNameID INTEGER REFERENCES SecGroupNames (SecGroupName_ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL ON CONFLICT ROLLBACKROLLBACK, ModID INTEGER REFERENCES Modules (Mod_ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL ON CONFLICT ROLLBACKROLLBACK, SecAccess_Read BOOLEAN DEFAULT (0) NOT NULL ON CONFLICT ROLLBACKROLLBACK, SecAccess_Write BOOLEAN DEFAULT (0) NOT NULL ON CONFLICT ROLLBACKROLLBACK, SecAccess_Delete BOOLEAN NOT NULL ON CONFLICT ROLLBACKROLLBACK DEFAULT (0))

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
